### ISSUE TITLE
LaTeX Warning: Unused global option

### ISSUE THREAD

**Issue by hair-splitter** [PhelypeOleinik/lipsum#13]
Compiling the following code, there is a LaTeX Warning: Unused global option(s): [12pt].

```
\documentclass[12pt]{article}
\usepackage{lipsum}
\begin{document}
\lipsum
\end{document}
```
Without `\usepackage{lipsum}` there is not warning.

**TeX-system:** TeX Live 2022 (updated: 2022/06/20)

**Comment by PhelypeOleinik** [comment]
Not a `lipsum` bug.  See latex3/latex2e#864.  This should be fixed in a few days with the next LaTeX patch release.
