### ISSUE TITLE
lipsum errors under expl3 check-declarations

### ISSUE THREAD

**Issue by 8573** [PhelypeOleinik/lipsum#3]
```latex
\documentclass{article}
\usepackage[check-declarations]{expl3}
\usepackage{lipsum}
\begin{document}
\lipsum[2]
\end{document}
```
If `expl3`'s option `check-declarations` is enabled, the document fails to build because of two "Inconsistent local/global assignment" errors in `lipsum` and one assignment to a variable not yet declared. This is perhaps not an important issue, but I tend to have `check-declarations` on so I notice this sort of thing.

**Comment by PhelypeOleinik** [comment]
Thanks for the report!  Can you show me the `.log` file, please?  Your example works fine for me...

**Comment by PhelypeOleinik** [comment]
Closing as this seems to be due to an outdated version.
